### ISSUE TITLE
Not support API V3

### ISSUE THREAD

**Issue by sylla-linoha** [miekg/xds#1]
I'm using Envoy version 1.20.7 and cannot use your repository, can I upgrade to use API v3?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/xds] Not support API V3 (Iss..." ]
>I'm using Envoy version 1.20.7 and cannot use your repository, can I upgrade to
>use API v3?

I will not to able to spend any time on this.

/Miek

--
Miek Gieben
